### PR TITLE
partial creature loot table update

### PR DESCRIPTION
**Pull request by kokeszko**
conditions included. all data based on old.wowhead.

more will come

### CODE REVIEW

**Comment by Salja** [comment]
thanks look good you have tested of startup errors etc ?

**Comment by kokeszko** [comment]
this update doesn't solve errors witch shows during server startup.
i'll look at them this evening

**Comment by Salja** [comment]
no i mean make this update new errors XD but i think not looks good wehn im @home i will look and push thanks

**Comment by kokeszko** [comment]
some bugz found. i'll pull request again

**Pull request closed without merging**
