### PR TITLE
Update 208_updatepack.sql

### PR DESCRIPTION
**Pull request by kokeszko**
Fixing creatures rank (Rare)

### CODE REVIEW

**Comment by danielsreichenbach** [comment]
I will review the updates against an old vanilla strategy guide which also lists the proper ranks for creatures.

Thanks for the submission :smile:

**Comment by MadMaxMangos** [comment]
Started confirming these now. Will reply again once I'm finished.

Not in book:
http://wowpedia.org/Death_Howl
http://wowpedia.org/Giggler
http://wowpedia.org/Gorefang
http://wowpedia.org/Gretheer
http://wowpedia.org/Hayoc
http://wowpedia.org/Hissperak
http://wowpedia.org/Ironback
http://wowpedia.org/Krellack
http://wowpedia.org/Krethis_the_Shadowspinner
http://wowpedia.org/Kurmokk
http://wowpedia.org/Lord_Condar
http://wowpedia.org/Mongress
http://wowpedia.org/Old_Cliff_Jumper
http://wowpedia.org/Old_Vicejaw
http://wowpedia.org/Olm_the_Wise
http://wowpedia.org/Oozeworm
http://wowpedia.org/Pridewing_Patriarch
http://wowpedia.org/Rippa
http://wowpedia.org/Ripscale
http://wowpedia.org/Shanda_the_Spinner
http://wowpedia.org/Snort_the_Heckler
http://wowpedia.org/Alshirr_Banebreath
http://wowpedia.org/Kaskk
http://wowpedia.org/Prince_Kellen
http://wowpedia.org/Prince_Raze
http://wowpedia.org/Snarlflare
http://wowpedia.org/Drogoth_the_Roamer
http://wowpedia.org/Huricanian
http://wowpedia.org/Molt_Thorn
http://wowpedia.org/Rumbler
http://wowpedia.org/Seeker_Aqualon
http://wowpedia.org/Stone_Fury
http://wowpedia.org/The_Husk
http://wowpedia.org/Vengeful_Ancient
http://wowpedia.org/War_Golem - Note: Special "Lock Down" ability.
http://wowpedia.org/Boulderheart
http://wowpedia.org/Brainwashed_Noble - Note: Deadmines
http://wowpedia.org/Marisa_du%27Paige - Note: Deadmines
http://wowpedia.org/Veyzhak_the_Cannibal - Note: Special "Enrage" ability.
http://wowpedia.org/Boahn - Note: Wailing Caverns
http://wowpedia.org/Burgle_Eye
http://wowpedia.org/Cursed_Centaur - Note: Maraudon
http://wowpedia.org/Dragonmaw_Battlemaster
http://wowpedia.org/Fingat
http://wowpedia.org/Gilmorian
http://wowpedia.org/Gluggle
http://wowpedia.org/Gravis_Slipknot
http://wowpedia.org/Grizzle_Snowpaw
http://wowpedia.org/Jalinde_Summerdrake
http://wowpedia.org/Jimmy_the_Bleeder
http://wowpedia.org/Lady_Zephris
http://wowpedia.org/Lord_Angler
http://wowpedia.org/Lord_Sinslayer

In Book:
http://wowpedia.org/Branch_Snapper
Notes:Listed as normal in book, made rare later. Immune to "Nature Damage"

http://wowpedia.org/Eck%27alom
Notes: Listed as normal in book, made rare later. Immune to "Special - Elemental Water"

http://wowpedia.org/Scald
Notes: Matches book. Immune to "Special - Elemental Fire"

http://wowpedia.org/Smoldar
Notes: Matches book. Immune to "Special - Elemental Earth"

Apothecary Falthis
http://wowpedia.org/Apothecary_Falthis
Notes: Immune to "Charm, Fear, Sleep"

Garneg Charskull
Notes: Immune to "Fire Magic"

Confirmed as far as line 1109 if anyone else wants to do the last few. Looks ok to me.

**Comment by kokeszko** [comment]
if anyone could look at Ambassador Bloodrage (entry 7895 , found in: THE BARRENS).
i've found only information that he was rare mob and he was removed in one of the patches. but i saw once a screenshot of him and he was rare elite. can someone confirm this?

**Comment by Joeys2233** [comment]
Ha ha ha

**Pull request merged**
