### PR TITLE
removed conditions for all recipes

### PR DESCRIPTION
**Pull request by kokeszko**
all recipes should be now available for all players, regardless of profession.

### CODE REVIEW

**Comment by Salja** [comment]
thanks i merge this in next days wehn release the new updatepack big thanks

**Comment by kokeszko** [comment]
do not apply this pull. as @cala said on forum, it might be wrong (some BoP repices are only visible to players with proper profession).

**Comment by kokeszko** [comment]
after discussion on forum, i'm reopening this pull again

**Comment by kokeszko** [comment]
it has been already applied via small update. closing

**Pull request closed without merging**
