### PR TITLE
Update _full_db/conditions.sql

### PR DESCRIPTION
**Pull request by kokeszko**
drop conditions for recipes. each player can get any recipe 
(without a proper profession)

### CODE REVIEW

**Comment by Salja** [comment]
thanks you right

**Comment by kokeszko** [comment]
i'll pull request with creature_loot_template.sql too

**Comment by Salja** [comment]
sounds nice pls not forgot to test XD

**Comment by Salja** [comment]
btw i forgot to say pls add the update querys in the dev file only full_db update is not needed i add all to full_db wehn release the updatepack thanks

**Comment by Salja** [comment]
for creature_loot_template you can use 

UPDATE `creature_loot_template` SET condition_id=0 WHERE condition_id IN (6,10,13,16);

here https://github.com/mangoszero/database/commit/a511c8da2bcfd85294b0dfd2e0a042e30ee2ecd8 i think yet is all done ?

**Comment by kokeszko** [comment]
yes, i have forgot about it.

**Pull request merged**
