### PR TITLE
Durotar Fixes Part 1

### PR DESCRIPTION
**Pull request by Evildead666**

### CODE REVIEW

**Comment by danielsreichenbach** [comment]
Thanks for your pull request. I will look into it, and review the changes.

**Comment by Evildead666** [comment]
would have merged it myself, but i won´t automerge. I can refork and automerge myself later today or tomorrow

**Comment by danielsreichenbach** [comment]
It's okay, I will do that today. :smile:

**Comment by Evildead666** [comment]
Thanks

**Pull request merged**
